using System;

public enum ResourceChangeReason
{
	Unknown = -1,
	ForTesting,
	WheelJackpot,
	WheelSingle,
	DailyCatch,
	TutorialItemUpgrade,
	TutorialFirstCrew,
	RestoreProgress,
	GemChestOpen,
	TournamentReward,
	QuestReward,
	AfterReviewReward,
	ChristmasCalendarDailyReward,
	PurchaseGemPack,
	PurchaseSpecialOffer,
	UnlockRandomCrew,
	UpgradeItem,
	UpgradeCrew,
	PurchaseItemChest,
	PurchaseTournamentEntry,
	OpenItemChestEarly,
	PurchaseBoostInShop,
	PurchaseSkillTreeReset,
	CrownLevelIncreased,
	UpgradeSkillTreeSkill,
	WatchAd,
	TutorialCrownExpIntro,
	FoundEasterEgg,
	UnlockEasterBasket,
	ItemChestOpen,
	GoalReward,
	UnlockEventTreasure,
	PurchaseFireworkPack,
	EventEnded,
	UseEventAbility,
	ItemCustomLogics,
	EventStartingBonus,
	EventConsumableForAd
}
